name: Deploy ShelfEcho

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to AWS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            cd ~/ShelfEcho || git clone https://github.com/SheriffAltTab/ShelfEcho.git ~/ShelfEcho
            cd ~/ShelfEcho
            git pull origin master
            
            echo "VITE_API_URL=https://shelfecho.site/api" > .env
            
            # 1. Збірка Фронтенду
            npm install
            npm run build
            
            # 2. Збірка Бекенду
            cd server
            npm install
            npm run build
            
            pm2 restart shelfecho || pm2 start dist/index.js --name "shelfecho"